name: CI

on: [push]

jobs:
  test:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: npm i
    - name: test
      run: npm test
    - name: coverage
      run: npm run coverage
    - name: Codecov
      uses: codecov/codecov-action@v1.0.5
      with:
        # Repository upload token - get it from codecov.io
        token: ${{ secrets.CODECOV_TOKEN }}
        # Path to coverage file to upload
        file: ./coverage/coverage.json
        # Flag upload to group coverage metrics (e.g. unittests | integration | ui,chrome)
        flags: unit
        # Specify whether or not CI build should fail if Codecov runs into an error during upload
        fail_ci_if_error: false
  build:
    runs-on: [ubuntu-latest]
  
    steps:
    - uses: actions/checkout@v2
    - uses: LucasRoesler/openfaas-action/build@v0.1.0
      name: Build
      with:
        path: "stack.yml"
        tag: "sha"
